source 'http://rubygems.org'

# gem 'rails', '3.0.1'
gem 'rails'

gem 'aasm'
gem 'ancestry'
gem 'bluecloth'
gem 'capistrano'
gem 'chronic'
gem 'daemon-spawn'
gem 'delayed_job'
gem 'faker'
gem 'fastercsv'
gem 'flickraw'
gem 'geoip'
gem 'geoplanet'
gem 'GeoRuby', :require => 'geo_ruby'
gem 'google_analytics'
gem 'hoptoad_notifier'
gem 'htmlentities'
gem 'machinist'
gem 'memcache-client'
gem 'mocha'
gem 'nokogiri'
gem 'oa-more'
gem 'oa-oauth'
gem 'oa-openid'
gem 'objectify-xml', :require => 'objectify_xml'
gem 'paperclip'
gem 'pg'
gem 'preferences', :git => 'git://github.com/rds/preferences.git'
gem 'rest-client', :require => 'rest_client'
gem 'right_aws'
gem 'right_http_connection'
gem 'spatial_adapter'
gem 'thinking-sphinx', '2.0.10'
gem 'ts-delayed-delta', :require => 'thinking_sphinx/deltas/delayed_delta'
gem 'will_paginate'


# group :test, :development do
#   gem "rspec-rails", "~> 2.0.1"
# end
