source 'http://rubygems.org'

gem 'rails'

gem 'aasm'
gem 'bborn-acts_as_taggable_on_steroids', :git => 'git://github.com/samoli/acts_as_taggable_on_steroids.git', :require => 'acts_as_taggable'
gem 'ancestry'
gem 'bluecloth'
gem 'capistrano'
gem 'chronic'
gem 'daemon-spawn'
gem 'delayed_job'
gem 'delayed_job_active_record'
# gem 'delayed_paperclip'
gem 'delayed_paperclip', '2.4.5.2', :git => 'git://github.com/tommeier/delayed_paperclip', :branch => 'fix_312'
gem 'devise'
gem 'devise-encryptable'
gem 'dynamic_form'
gem 'faker'
gem 'fastercsv'
gem 'flickraw'
gem "friendly_id", "~> 4.0.1"
gem 'geoplanet'
gem 'GeoRuby', :require => 'geo_ruby'
gem 'google_analytics'
# gem 'hoptoad_notifier'
gem 'htmlentities'
gem 'machinist'
gem 'memcache-client'
gem 'mocha'
gem 'nokogiri'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-flickr'
gem 'omniauth-openid'
gem 'objectify-xml', :require => 'objectify_xml'
gem 'paperclip'
gem 'pg'
gem 'preferences', :git => 'git://github.com/Titinux/preferences.git'
gem 'rack-google_analytics'
gem 'rest-client', :require => 'rest_client'
gem 'right_aws'
gem 'right_http_connection'
gem 'rinku', :require => 'rails_rinku'
gem 'spatial_adapter'
gem 'thinking-sphinx', '2.0.10'
gem 'ts-delayed-delta', :require => 'thinking_sphinx/deltas/delayed_delta'
gem 'will_paginate'


group :test, :development do
  gem "rspec-rails" #, "~> 2.0.1"
end
