# Populates a deterministic, fully-populated dashboard (/home) for the visual
# test, exercising the dashboard's timeline item types plus announcements in
# both placements.
#
# Every login/name/body is fixed so snapshots are stable, and the command is
# idempotent: the e2e DB is long-lived and never reset between runs, so we tear
# down the previous seed (and purge the owner's prior timeline items from
# Elasticsearch) and rebuild identical data on each run.
#
# Timeline items are Elasticsearch-backed UpdateActions generated by the app's
# real notification flow. In the test env has_subscribers is disabled and
# Delayed::Job isn't worked off, so we enable subscribers and run jobs inline.
#
# Returns the owner's login credentials so the spec can sign in.
#
#   app( "seed_dashboard", {} )   # => { "email" => ..., "password" => ... }

password = "DashboardPass123!"
note = ->( msg ) { logger.warn( "[seed_dashboard] #{msg}" ) }

find_or_make_user = lambda do | login, name, curator: false, organizer: false |
  user = User.find_by( login: login )
  unless user
    user = User.make!( login: login, name: name, email: "#{login}@example.com", password: password )
    UserPrivilege.make!( user: user, privilege: UserPrivilege::INTERACTION )
  end
  user.roles << Role.find_or_create_by!( name: "curator" ) if curator && !user.is_curator?
  # Creating a project requires the organizer privilege (normally earned with 50
  # verifiable observations); grant it directly so the seed doesn't need them.
  if organizer && !user.user_privileges.exists?( privilege: UserPrivilege::ORGANIZER )
    UserPrivilege.make!( user: user, privilege: UserPrivilege::ORGANIZER )
  end
  user
end

owner = find_or_make_user.call( "e2edashboardowner", "Dashy McDashface" )
alice = find_or_make_user.call( "e2eactoralice", "Alice Fieldnotes", organizer: true )
bruno = find_or_make_user.call( "e2eactorbruno", "Bruno Trailhead" )
clara = find_or_make_user.call( "e2eactorclara", "Clara Meadowlark", organizer: true )
curator = find_or_make_user.call( "e2eseedcurator", "Cora Curator", curator: true )
actors = [alice, bruno, clara]

# Tag every seeded taxon with a fixed creator so the teardown can find and
# destroy them; otherwise they'd accumulate ~1 row per name per run forever.
species = ->( name ) { Taxon.make!( name: name, rank: Taxon::SPECIES, is_active: true, creator: curator ) }

previous_has_subscribers = CONFIG.has_subscribers
previous_delay_jobs = Delayed::Worker.delay_jobs
CONFIG.has_subscribers = :enabled
Delayed::Worker.delay_jobs = false
begin
  # ---- Idempotent teardown ---------------------------------------------------
  # Determinism hinges on purging the owner's timeline items; destroying the
  # backing records keeps the DB from growing without bound. Destroying
  # observations cascades to their comments/identifications/OFVs, whose
  # after_destroy hooks purge the related UpdateActions.
  ( [owner] + actors ).each {| u | u.observations.destroy_all }
  owner.friendships.destroy_all
  owner.project_users.destroy_all
  Subscription.where( user_id: owner.id ).delete_all
  Project.where( user_id: actors.map( &:id ) ).destroy_all
  Place.where( name: "Seed Sanctuary" ).destroy_all
  Post.where( user_id: ( actors + [owner] ).map( &:id ) ).destroy_all
  # Flags don't cascade when their flaggable observation is destroyed above, so
  # purge the ones the actors raised explicitly.
  Flag.where( user_id: actors.map( &:id ) ).destroy_all
  # Taxa (and the taxon change that references them) are orphaned once their
  # observations are gone; drop them so the taxa table doesn't grow each run.
  # Changes first — taxon_change_taxa reference the taxa via FK.
  TaxonChange.by( curator ).destroy_all
  Taxon.where( creator_id: curator.id ).destroy_all
  Announcement.where(
    placement: [Announcement::USERS_DASHBOARD, Announcement::USERS_DASHBOARD_SIDEBAR]
  ).destroy_all
  # Catch any leftover items the owner still subscribes to (friend obs, mentions,
  # taxon/place/project/committed updates) from earlier runs.
  prior = owner.recent_notifications( per_page: 500 )
  UpdateAction.delete_and_purge( ["id IN (?)", prior.map( &:id )] ) unless prior.empty?

  # ---- activity: a resolved flag you're subscribed to ------------------------
  # Flags notify their subscribers on update when the comment changes (and the
  # subscriber isn't the resolver), rendering as a flag activity item.
  begin
    flagged_obs = Observation.make!(
      user: alice, taxon: species.call( "Corvus corax" ),
      latitude: 45.5, longitude: -122.6, place_guess: "Oregon, USA"
    )
    flag = Flag.make!( flaggable: flagged_obs, user: bruno, flag: Flag::INAPPROPRIATE )
    Subscription.create!( user: owner, resource: flag )
    flag.update!( resolved: true, resolver: curator, comment: "Reviewed — no action needed." )
  rescue StandardError => e
    note.call( "flag activity update skipped: #{e.class}: #{e.message}" )
  end

  # ---- mention ---------------------------------------------------------------
  mention_obs = Observation.make!(
    user: clara, taxon: species.call( "Ursus americanus" ),
    latitude: 44.0, longitude: -110.0, place_guess: "Wyoming, USA"
  )
  Comment.make!(
    parent: mention_obs, user: alice,
    body: "Nice one @#{owner.login} — is this the same spot as last year?"
  )

  # ---- following: new observations from someone you follow -------------------
  Friendship.create!( user: owner, friend: bruno ) # auto-subscribes owner to bruno
  # Several observations from a followed user group into one created_observations
  # item that renders a grid of thumbnails.
  ["Bombus impatiens", "Apis mellifera", "Xylocopa virginica",
   "Halictus ligatus", "Agapostemon virescens"].each do | name |
    Observation.make!(
      user: bruno, taxon: species.call( name ),
      latitude: 41.0, longitude: -73.0, place_guess: "New York, USA"
    )
  end

  # ---- taxon subscription: new observation of a taxon you follow -------------
  followed_taxon = species.call( "Papilio machaon" )
  Subscription.create!( user: owner, resource: followed_taxon )
  Observation.make!(
    user: alice, taxon: followed_taxon,
    latitude: 40.0, longitude: -74.0, place_guess: "New Jersey, USA"
  )

  # ---- project ecosystem: project post, curator change, invitation, add ------
  begin
    project = Project.make!( user: alice, title: "Meadow Pollinators of the Northeast" )
    ProjectUser.make!( user: owner, project: project ) # auto-subscribes owner to the project
    Post.make!(
      parent: project, user: alice, title: "Season kickoff",
      body: "Welcome to another season of pollinator surveys!", published_at: Time.now
    )
    ProjectUser.make!( user: bruno, project: project ).update!( role: "curator" )
    ProjectUserInvitation.make!(
      project: Project.make!( user: clara, title: "Backyard Birds" ),
      user: clara, invited_user: owner
    )
    # A bare observation of yours with no other activity, so the project add is
    # its only timeline item.
    added_obs = Observation.make!(
      user: owner, taxon: species.call( "Sciurus carolinensis" ),
      latitude: 37.8651, longitude: -119.5383, place_guess: "Yosemite National Park, CA, USA"
    )
    ProjectObservation.make!( observation: added_obs, project: project, user: alice )
  rescue StandardError => e
    note.call( "project-ecosystem updates skipped: #{e.class}: #{e.message}" )
  end

  # ---- place subscription: new observation in a place you follow -------------
  begin
    # Build unsaved: a Place validates geometry presence on create, so set the
    # geom before the first save (mirrors the make_place_with_geom spec helper).
    place = Place.make( name: "Seed Sanctuary", latitude: 0.5, longitude: 0.5 )
    place.save_geom( GeoRuby::SimpleFeatures::Geometry.from_ewkt( "MULTIPOLYGON(((0 0,0 1,1 1,1 0,0 0)))" ) )
    place.save!
    Subscription.create!( user: owner, resource: place )
    Observation.make!(
      user: clara, taxon: species.call( "Anas platyrhynchos" ),
      latitude: 0.4, longitude: 0.4, place_guess: "Seed Sanctuary"
    )
  rescue StandardError => e
    note.call( "place-subscription update skipped: #{e.class}: #{e.message}" )
  end

  # ---- committed taxon change ------------------------------------------------
  # A commit notifies users who own a record (here, an observation) of the input
  # taxon — not taxon subscribers — so the owner needs one.
  begin
    input_taxon = species.call( "Vanessa cardui" )
    output_taxon = species.call( "Vanessa kershawi" )
    Observation.make!(
      user: owner, taxon: input_taxon,
      latitude: 34.0, longitude: -118.0, place_guess: "California, USA"
    )
    # Build unsaved: a TaxonSwap validates it has both inputs and outputs, so
    # attach them before the first save (mirrors the make_taxon_swap helper).
    swap = TaxonSwap.make( user: curator )
    swap.add_input_taxon( input_taxon )
    swap.add_output_taxon( output_taxon )
    swap.save!
    swap.committer = curator
    swap.commit
  rescue StandardError => e
    note.call( "committed taxon-change update skipped: #{e.class}: #{e.message}" )
  end

  # ---- announcements ---------------------------------------------------------
  Announcement.make!(
    placement: Announcement::USERS_DASHBOARD, user: owner,
    body: "<strong>Welcome back!</strong> Here's the latest activity on your observations."
  )
  Announcement.make!(
    placement: Announcement::USERS_DASHBOARD_SIDEBAR, user: owner,
    body: "Tip: subscribe to a taxon or place to see new observations here."
  )
ensure
  Delayed::Worker.delay_jobs = previous_delay_jobs
  CONFIG.has_subscribers = previous_has_subscribers
end

# Make the freshly-indexed UpdateActions searchable before the dashboard queries.
UpdateAction.__elasticsearch__.refresh_index!

[{ "email" => owner.email, "password" => password }]
