version: "2"
services:

  redis:
    container_name: redis
    image: redis:6.0.3
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  memcached:
    container_name: memcached
    image: memcached:1.6.6
    ports:
      - 11211:11211

  rails:
    container_name: rails
    image: rails:1.0
    environment:
      RAILS_ENV: development
      INAT_DB_HOST: pg
      INAT_DB_USER : 'inaturalist'
      INAT_DB_PASS: 'CHANGE_ME'
      INAT_DB_NAME: inaturalist_production
    ports:
      - 3000:3000
    extra_hosts:
      - "pg:CHANGE_ME"
      - "es:CHANGE_ME"

  api:
    container_name: api
    image: api:1.0
    environment:
      NODE_ENV: development
      INAT_DB_HOST: pg
      INAT_DB_USER : 'inaturalist'
      INAT_DB_PASS: 'CHANGE_ME'
      INAT_DB_NAME: inaturalist_production
      INAT_ES_HOST: es
      INAT_ES_INDEX_PREFIX: production
      INAT_REDIS_HOST: redis
      INAT_WEB_HOST: host.docker.internal
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "pg:CHANGE_ME"
      - "es:CHANGE_ME"

volumes:
  redis_data:
