access_key_id: <%= ENV.fetch("INAT_AWS_ACCESS_KEY") { "INAT_AWS_ACCESS_KEY" } %>
secret_access_key: <%= ENV.fetch("INAT_AWS_SECRET_ACCESS_KEY") { "INAT_AWS_SECRET_ACCESS_KEY" } %>
cloudfront_distribution: <%= ENV.fetch("INAT_AWS_CLOUDFRONT_DISTRIBUTION") { "INAT_AWS_CLOUDFRONT_DISTRIBUTION" } %>