
---
  user_name: <%= ENV.fetch("INAT_SMPT_USER_NAME") %>
  password: <%= ENV.fetch("INAT_SMPT_PASSWORD") %>
  domain: <%= ENV.fetch("INAT_SMPT_DOMAIN") %>
  address: <%= ENV.fetch("INAT_SMPT_ADDRESS") %>
  port: <%= ENV.fetch("INAT_SMPT_PORT") %>
  authentication: :plain
  enable_starttls_auto: true