#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
Delayed::Worker.logger = Logger.new(File.join(Rails.root, 'log', 'dj.log'))
