# frozen_string_literal: true

# Storage for the flipper gem's feature flags. See WEB-1074,
# doc/feature_flags_ab_options.md, and lib/feature_flagging.rb.
#
# Generated by `rails g flipper:active_record`, with the generator's
# `length: { value: 255 }` index option removed — that is a MySQL prefix-length
# option and this app is Postgres/PostGIS only. Flipper stores one row per
# actor, so index entries stay well under Postgres's btree size limit.
class CreateFlipperTables < ActiveRecord::Migration[6.1]
  def up
    create_table :flipper_features do | t |
      t.string :key, null: false
      t.timestamps null: false
    end
    add_index :flipper_features, :key, unique: true

    create_table :flipper_gates do | t |
      t.string :feature_key, null: false
      t.string :key, null: false
      t.text :value
      t.timestamps null: false
    end
    add_index :flipper_gates, [:feature_key, :key, :value], unique: true
  end

  def down
    drop_table :flipper_gates
    drop_table :flipper_features
  end
end
