export const DRAG = "DRAG";
export const APPEND_OBS_CARDS = "APPEND_OBS_CARDS";
export const UPDATE_OBS_CARD = "UPDATE_OBS_CARD";
export const REMOVE_OBS_CARD = "REMOVE_OBS_CARD";
export const SUBMIT_OBSERVATIONS = "SUBMIT_OBSERVATIONS";
export const CREATE_BLANK_OBS_CARD = "CREATE_BLANK_OBS_CARD";
export const SELECT_OBS_CARDS = "SELECT_OBS_CARDS";
export const UPDATE_SELECTED_OBS_CARDS = "UPDATE_SELECTED_OBS_CARDS";
