name: Rails Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build/Test 
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgis/postgis:13-3.2
        env:
          POSTGRES_USER: inaturalist
          POSTGRES_PASSWORD: inaturalist
          POSTGRES_DB: inaturalist_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        # Note that these letter prefix patterns must match existing files or
        # Github will error out of the build
        spec_pattern:
          - spec/models/{a,b,c,d,e,f,g}*_spec.rb
          - spec/models/{i,l,m}*_spec.rb
          - spec/models/oauth*_spec.rb spec/models/observation_{f,b}*_spec.rb
          - spec/models/observation_{g,l,p,r}*_spec.rb
          - spec/models/observation_s*_spec.rb spec/models/observation_spec.rb spec/models/observation_p*_spec.rb
          - spec/models/p{a,h,l,o}*_spec.rb
          - spec/models/pr*_spec.rb
          - spec/models/{q,s,u,w,y}*_spec.rb
          - spec/models/taxon_{c,d,f,l,m,n,p,r,s}*_spec.rb
          - spec/models/taxon_spec.rb spec/models/trip_*_spec.rb
          - spec/controllers/{a,c,e,f,g,i,l,m}*_spec.rb
          - spec/controllers/o*_spec.rb
          - spec/controllers/{p,q,r,s,t,u,v,w}*_spec.rb
          - spec/helpers spec/initializers spec/lib spec/views spec/features

    steps:
    - uses: actions/checkout@v4

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      uses: miyataka/elastic-github-actions/elasticsearch@feature/plugin_support
      with:
        stack-version: 8.15.3
        plugins: analysis-kuromoji

    - name: Ensure elasticsearch is reachable
      run: |
        curl --verbose --show-error http://localhost:9200

    - name: Install dependencies
      run: |
        sudo apt-get -qq update --fix-missing
        sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev gdal-bin proj-bin proj-data libgeos-dev libgeos++-dev libproj-dev ffmpeg

    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: npm install
    - run: npm run webpack

    - name: Before script
      run: ci/scripts/before_script.sh
      env:
        PGHOST: 0.0.0.0
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        TRAVIS: true
        CI: true

    - name: Run specs
      run: bundle exec rspec ${{ matrix.spec_pattern }}
      env:
        PGHOST: 0.0.0.0
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        TRAVIS: true
        TRAVIS_CI: true
        CI: true
