name: Rails Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build/Test 
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgis/postgis:13-3.2
        env:
          POSTGRES_USER: inaturalist
          POSTGRES_PASSWORD: inaturalist
          POSTGRES_DB: inaturalist_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        # Note that these letter prefix patterns must match existing files or
        # Github will error out of the build
        spec_pattern:
          - spec/models/guide_section_spec.rb
          - spec/models/guide_user_spec.rb
    steps:
    - uses: actions/checkout@v4

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      uses: miyataka/elastic-github-actions/elasticsearch@feature/plugin_support
      with:
        stack-version: 8.15.3
        plugins: analysis-kuromoji

    - name: Ensure elasticsearch is reachable
      run: |
        curl --verbose --show-error http://localhost:9200

    - name: Install dependencies
      run: |
        sudo apt-get -qq update --fix-missing
        sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev gdal-bin proj-bin proj-data libgeos-dev libgeos++-dev libproj-dev ffmpeg

    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: npm install
    - run: npm run webpack

    - name: Before script
      run: ci/scripts/before_script.sh
      env:
        PGHOST: 0.0.0.0
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        TRAVIS: true
        CI: true

    - name: Run specs
      run: bundle exec rspec ${{ matrix.spec_pattern }}
      env:
        PGHOST: 0.0.0.0
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        TRAVIS: true
        TRAVIS_CI: true
        CI: true

    - name: Run restricted eslint
      run: npm run eslint app/webpack/computer_vision
